### ISSUE TITLE
Add a way to configure Client IP value

### ISSUE THREAD

**Issue by bfeldmanpublic** [castle/castle-java#29]
We should offer a simple way to configure the header that should be checked for the true client ip via our SDKs.

For example, in our Java SDK, we automatically set the client ip to the value of `REMOTE_ADDRESS`. This is done here: https://github.com/castle/castle-java/blob/09ebe7ab832fa5f54f82b4fce66b9f209e4fd17d/src/main/java/io/castle/client/internal/utils/CastleContextBuilder.java#L68

However, many customers need to change this to `X-Forwarded-For` or `true-client-ip` for example. It would be great if they could easily change that in a config file

**Comment by sebastiansimson** [comment]
Resolved in #45
