### ISSUE TITLE
Add additional timestamps to Verdict

### ISSUE THREAD

**Issue by twomoose** [castle/castle-java#50]
Sending `"include": "timestamps"` in authenticate request bodies results additional info in the response, for example:
```json
{
  "action": "deny",
  "user_id": "1234",
  "device_token": "5678",
  "created_at": "2019-02-14T02:43:53.405Z",
  "last_seen_at": "2019-03-06T01:55:51.839Z",
  "approved_at": null,
  "escalated_at": "2019-02-26T10:12:43.836Z",
  "mitigated_at": null
}
```

I understand these were introduced experimentally, however they are quite useful for measuring timing, and aid in tracking things on the client side.

**Comment by joladev** [comment]
That's a great idea, and we've experimented with allowing access to the experimental properties through a special property over in the .NET SDK. We're looking to get this functionality ported to this SDK soon.

Thanks for the feedback!

**Comment by joladev** [comment]
Support for this was released in https://github.com/castle/castle-java/releases/tag/v1.4.2
