### ISSUE TITLE
Support for custom authenticate and track payloads

### ISSUE THREAD

**Issue by sebastiansimson** [castle/castle-java#54]
Add support for custom authenticate and track payloads. Add methods `buildTrackRequest(CastleMessage request)`, `sendTrackRequest(JsonElement request)`, `buildAuthenticateRequest(CastleMessage request)`, `sendAuthenticateRequest(JsonElement request)`.

Build methods are used to get the standard payload json object, which can be expanded with custom fields. The JsonElement is then sent using the send methods.

**Comment by wallin** [comment]
#56
